### ISSUE TITLE
"List All User's Photos" hangs on "Loading images and videos"

### ISSUE THREAD

**Issue by Stsosz** [gabrieljmj/DInstagram#1]
Does not work on OSX 10.11.5 or windows 10. 

![Screenshot](https://cloud.githubusercontent.com/assets/7494858/15803559/eb9b67fc-2ab1-11e6-9bb5-e28cd9d50574.png)

**Comment by gabrieljmj** [comment]
I fixed the loading problem :+1: However I have another problem: is not possible anymore get all posts from a user with Instagram's API.
